call plug#begin('~/.vim/plugged')

Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'mattn/vim-lsp-settings'
Plug 'Yggdroot/indentLine'
Plug 'bronson/vim-trailing-whitespace'
Plug 'vim-airline/vim-airline-themes'
Plug 'osyo-manga/vim-anzu'
Plug 'elzr/vim-json'
Plug 'liuchengxu/vim-clap'
Plug 'rust-lang/rust.vim'
Plug 'lambdalisue/gina.vim'
Plug 'rbtnn/vim-mrw'
Plug 'cocopon/iceberg.vim'
Plug 'cespare/vim-toml'
Plug 'tpope/vim-markdown'
Plug 'kannokanno/previm'
Plug 'rhysd/vim-clang-format'
Plug 'tyru/open-browser.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'mattn/emmet-vim'
Plug 'vim-jp/autofmt'
Plug 'cocopon/vaffle.vim'
Plug 'mattn/vim-goimports'
Plug 'mattn/vim-sonictemplate'
Plug 'lambdalisue/fern.vim'
Plug 'thinca/vim-quickrun'
Plug 'vim-jp/vimdoc-ja'
Plug 'pechorin/any-jump.vim'
Plug 'lambdalisue/readablefold.vim'
Plug 'lambdalisue/vim-backslash'
Plug 'pocke/keycast.vim'
Plug 'pocke/vanner'
Plug 'higashi000/vimvimsemi'
Plug 'vim-denops/denops.vim'
Plug 'higashi000/dps-kakkonan'

call plug#end()

set number

" colorscheme---{{{
syntax enable
colorscheme iceberg
set background=dark
"}}}

" indent setting {{{
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smarttab
set cindent
" if .py file open
augroup PythonIndent
  autocmd!
  autocmd FileType python set tabstop=4 softtabstop=4 shiftwidth=4
augroup END

augroup Stpl
  autocmd!
  autocmd FileType stpl set noexpandtab
augroup END
" }}}

" highlight in search result
set hlsearch
" highlight in cursor line, col
set cursorline
set cursorcolumn
" folding setting
set foldmethod=marker

set tabline=2

" enable backspace
set backspace=indent,eol,start

" vim-jp/vimdoc-ja
set helplang=ja,en

"clipboard
set clipboard^=unnamedplus

" spell check
"setlocal spell spelllang=en_us
"set spelloptions+=camel

"set nostartofline

" buffer move
noremap <silent><C-x> :bdelete<CR>
noremap <silent><C-h> :bprevious<CR>
noremap <silent><C-l> :bnext<CR>

" display cursor pos
set ruler
" error bell
set noerrorbells
" status line
set laststatus=2

" highlight cancel
noremap <silent> <ESC><ESC> :noh<CR>

" `s;;` to `std::`
inoremap s;; std::

" set leaderkey
let mapleader = "\<Space>"

" `;` to ':' in normal mode
noremap ; :

" escape terminal mode
tnoremap <C-[> <C-\><C-n>

" turn back
noremap j gj
noremap k gk

" " auto save --- {{{
" augroup autoSave
"   autocmd!
"   autocmd CursorHold,CursorHoldI * call Higashi000AutoSave()
" augroup END
"
" " auto save
" function! Higashi000AutoSave()
"   " ¿¿¿¿¿¿¿¿¿¿¿¿¿NERDTree¿¿¿¿¿¿¿¿¿¿¿¿¿¿
"   let notAutoSavePattern = '\v^NERD_tree_\v\d*|\v^\v$'
"   if match(expand('%'), notAutoSavePattern) != 0 && !&readonly
"     :w
"   endif
" endfunction
" " }}}

" line number {{{
"augroup lineNumber
"  autocmd!
"  autocmd CursorMoved,CursorMovedI * call SetLineNumber(1)
"  autocmd CursorHold,CursorHoldI * call SetLineNumber(0)
"augroup END
"
"function! SetLineNumber(whichOpt)
"  if a:whichOpt
"    set relativenumber
"    set nonumber
"    highlight LineNr ctermfg=166
"  else
"    set number
"    set norelativenumber
"    highlight LineNr ctermfg=239
"  endif
"endfunction
" }}}

" Respect for https://github.com/yukiycino-dotfiles/dotfiles/blob/master/.vimrc {{{
nnoremap <Left>  :vertical resize -1<CR>
nnoremap <Right> :vertical resize +1<CR>
nnoremap <Up>    :resize -1<CR>
nnoremap <Down>  :resize +1<CR>
" }}}

" vim-json
let g:vim_json_syntax_conceal = 0

" asyncomplete
let g:asyncomplete_auto_popup = 1

" markdown
nnoremap <silent> <C-p> :PrevimOpen<CR>
let g:vim_markdown_folding_disabled=1
let g:previm_enable_realtime=1

" complement setting {{{
" vim-lsp command
nnoremap <silent> <Leader>d :LspDefinition<CR>
nnoremap <silent> <Leader>f :LspDocumentFormat<CR>
nnoremap <silent> <Leader>h :LspHover<CR>
nnoremap <silent> <Leader>r :LspRename<CR>
nnoremap <silent> <Leader>a :LspCodeAction<CR>
nnoremap <silent> <Leader>ne :LspNextError<CR>
nnoremap <silent> <Leader>pe :LspPreviousError<CR>
nnoremap <silent> <Leader>td :LspTypeDefinition<CR>

" asyncomplete-file
au User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
    \ 'name': 'file',
    \ 'whitelist': ['*'],
    \ 'priority': 10,
    \ 'completor': function('asyncomplete#sources#file#completor')
    \ }))



" }}}

" airline {{{
let g:airline_powerline_fonts = 1
let g:airline_theme = 'molokai'
let g:airline#extensions#tabline#enabled = 1
" }}}


" emmet-vim
let g:user_emmet_leader_key='<C-y>'

" autofmt
set formatexpr=autofmt#japanese#formatexpr()
let autofmt_allow_over_tw=1

" echodoc.vim
set cmdheight=2
let g:echodoc#enable_at_startup = 1

" rust.vim
let g:rustfmt_autosave = 1

" QuickRun
noremap <silent> <Leader>q :QuickRun<CR>

" sonictemplate.vim
let g:sonictemplate_vim_template_dir = expand('~/dotfiles/vim/template')

" dps-kakkonan surround text to backets example keymap
vmap ( <Plug>(dps_kakkonan_surround_parenthesis)
vmap { <Plug>(dps_kakkonan_surround_curly)
vmap [ <Plug>(dps_kakkonan_surround_square)
vmap " <Plug>(dps_kakkonan_surround_doublequote)
vmap ' <Plug>(dps_kakkonan_surround_singlequote)
vmap ` <Plug>(dps_kakkonan_surround_backquote)

" dps-kakkonan replace brackets example keymap
map rp( <Plug>(dps_kakkonan_replace_parenthesis)
map rp{ <Plug>(dps_kakkonan_replace_curly)
map rp[ <Plug>(dps_kakkonan_replace_square)
map rp" <Plug>(dps_kakkonan_replace_doublequote)
map rp' <Plug>(dps_kakkonan_replace_singlequote)
map rp` <Plug>(dps_kakkonan_replace_backquote)

set runtimepath+=~/dps-kakkonan

let g:asyncomplete_auto_popup = 1
