[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
depends = ['deoplete.nvim']
build = 'bash install.sh'
# LanguageClient-neovim settings --- {{{
hook_add = '''
set hidden
let g:LanguageClient_serverCommands = {
      \ 'c': ['clangd'],
      \ 'cpp': ['clangd'],
      \'d': ['dls'],
      \'ruby': ['solargraph', 'stdio'],
      \'python': ['pyls'],
      \ }
let g:LanguageClient_useVirtualText = 0
let g:LanguageClient_loadSettings = 1
let g:LanguageClient_settingsPath = expand('$HOME/.config/nvim/toml/LanguageClientSetting.json')
let g:LanguageClient_hasSnippetSupport = 0

nnoremap K :call LanguageClient#textDocument_hover()<CR>
nnoremap F :call LanguageClient#textDocument_formatting()<CR>
'''
hook_source = '''
set completefunc=LanguageClient#complete
'''
# }}}

[[plugins]]
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'higashi000/Kakkonan'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = '<C-T>'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
# on_i = 1
#sonictemplate---{{{
hook_add = '''
let g:sonictemplate_vim_template_dir = [
    \'~/.config/nvim/template'
    \]
'''

#---}}}

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
# hook_add {{{
hook_add = '''
let g:NERDTreeDirArrow = 1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let g:NERDTreeDirArrowExpandable = '→'
let g:NERDTreeDirArrowCollapsible = '↓'
nnoremap <silent> <C-n> :NERDTreeToggle<CR>
'''
#}}}

[[plugins]]
repo = 'vim-airline/vim-airline'
# airline settings ---{{{
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline_theme = 'bubblegum'
let g:airline#extensions#tabline#enabled = 1

noremap <silent><Space>x :bdelete<CR>
noremap <silent><Space>h :bprevious<CR>
noremap <silent><Space>l :bnext<CR>
'''
# airline settings ---}}}

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
