[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-necovim.vim'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'liuchengxu/vim-clap'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'taigacute/gruvbox9'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'
